### ISSUE TITLE
Why does it not prompt me to enter SSH password?

### ISSUE THREAD

**Issue by spookey0188** [blacklanternsecurity/TREVORproxy#7]
I want to use password not key. Why was this removed?

**Comment by TheTechromancer** [comment]
This was never a feature in trevorproxy, for the sole reason that passing passwords via the command line (and storing them in memory) is not secure. Setting up key authentication is easy, and can be accomplished by running `ssh-keygen`, then `ssh-copy-id user@your.server.com` for each server you wish to use with trevorproxy.
